SET LINES 150 PAGES 1000;
COL COMMAND_ID FOR A20;
COL START_TIME FOR A20;
COL TIME_TAKEN_DISPLAY FOR A18;
COL STATUS FORMAT A15;
COL INPUT_TYPE FOR A20;
COL OUTDEVICE FOR A10;
COL INPUTBYTES FOR A10;
COL OUT_BYTES FOR A10;
COL OUT_PERSEC FOR A10;
SELECT
COMMAND_ID, TO_CHAR(START_TIME, 'DD-Mon-RR HH24:MI:SS')START_TIME, TIME_TAKEN_DISPLAY, STATUS, INPUT_TYPE, OUTPUT_DEVICE_TYPE OUTDEVICE, INPUT_BYTES_DISPLAY INPUTBYTES,
OUTPUT_BYTES_DISPLAY OUT_BYTES, OUTPUT_BYTES_PER_SEC_DISPLAY OUT_PERSEC
FROM V$RMAN_BACKUP_JOB_DETAILS
ORDER BY 1 DESC;

