SET LINES 250 PAGES 5000 TIMING ON TRIM ON;
--Check DB information
COL PLATFORM_NAME FOR A30;
COL DB_UNIQUE_NAME FOR A15;
COL CURRENT_SCN FOR A20;
COL HOST_NAME FOR A30;
SELECT NAME,DB_UNIQUE_NAME,INSTANCE_NAME,DBID,HOST_NAME,PLATFORM_NAME,OPEN_MODE,STATUS,LOG_MODE,DATABASE_ROLE,TO_CHAR(CURRENT_SCN)CURRENT_SCN FROM V$DATABASE X,V$INSTANCE Y;

--Check maximum sequence
SELECT /*Primary*/ MAX(SEQUENCE#) FROM V$ARCHIVED_LOG;

--Check destination error on primary DB
COL DESTINATION FOR A35;
SELECT /*Check destination status on primary*/ THREAD#, DEST_ID, DESTINATION, GVAD.STATUS, ERROR, FAIL_SEQUENCE FROM GV$ARCHIVE_DEST GVAD, GV$INSTANCE GVI WHERE GVAD.INST_ID = GVI.INST_ID AND DESTINATION IS NOT NULL ORDER BY THREAD#, DEST_ID;
