#!/bin/bash
source /home/oracle/.bash_profile; export NLS_DATE_FORMAT='DD-Mon-RR HH24:MI:SS'; export TGL=`date +%Y%m%d`; export DIR=/home/oracle/backup;
$ORACLE_HOME/bin/rman target=/ log=/home/oracle/backup/RMAN-fullbackup_swo_`date +%Y%m%d`.log << EOF
run{
	CONFIGURE DEVICE TYPE DISK PARALLELISM 2;
	CROSSCHECK BACKUP;
    DELETE NOPROMPT EXPIRED BACKUP;
    DELETE NOPROMPT BACKUP;
    CROSSCHECK ARCHIVELOG ALL;
    DELETE NOPROMPT EXPIRED ARCHIVELOG ALL;
    SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT';
    backup database format '$DIR/INC0_%I%d%T_%s_%p.bkp';
    BACKUP AS COMPRESSED BACKUPSET ARCHIVELOG ALL TAG 'ARCHIVELOGS_$TGL' FORMAT '$DIR/ARC_%I%d%T_%s_%p.bkp';
    BACKUP AS COMPRESSED BACKUPSET CURRENT CONTROLFILE TAG 'PRIMCTRL_$TGL' FORMAT '$DIR/CTRL_%I%d%T_%s_%p.bkp';
    BACKUP AS COMPRESSED BACKUPSET CURRENT CONTROLFILE FOR STANDBY TAG 'STBYCTRL_$TGL' FORMAT '$DIR/STBY_%I%d%T_%s_%p.bkp';
    BACKUP AS COMPRESSED BACKUPSET SPFILE TAG 'SPFile_$TGL' FORMAT '$DIR/SPF_%I%d%T_%s_%p.bkp';
    CONFIGURE DEVICE TYPE DISK CLEAR;
	}
EOF